config/routes.rb
Slides::Application.routes.draw do
  resources :roles

  devise_for :users

end

app/models/role.rb
class Role < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_and_belongs_to_many :users
  
  def self.roles
    %w(security admin user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, 
         :recoverable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

  
  has_and_belongs_to_many :roles
 
  #declarative authorization expects a role_symbols method that returns an array of symbols of role names
  def role_symbols
    roles.map {|role| role.name.to_sym}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  protected

  def permission_denied
    render :template => 'shared/permission_denied.html.erb', :layout => 'public'
  end
end

app/controllers/original_template_controller.rb
class OriginalTemplateController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  filter_resource_access
  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/template_helper.rb
module TemplateHelper
  def render_or_default(partial, default = partial)
    render :partial => partial
  rescue ActionView::MissingTemplate
    begin
      render :partial => "layouts/#{default}"
    rescue ActionView::MissingTemplate
      nil
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<title>Jungleland</title>

<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
<meta name="author" content="Erwin Aligam - styleshout.com" />
<meta name="description" content="Site Description Here" />
<meta name="keywords" content="keywords, here" />
<meta name="robots" content="index, follow, noarchive" />
<meta name="googlebot" content="noarchive" />

<link rel="stylesheet" type="text/css" media="screen" href="/stylesheets/screen.css" />
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/stylesheets/ie6.css" media="screen" /><![endif]-->
  <%= javascript_include_tag :all %>
  <%= yield(:head) %>
</head>

<body>

<!-- wrap -->
<div id="wrap">

	<!-- header -->
	<div id="header">			
	
		<a name="top"></a>
		
		<h1 id="logo-text"><a href="index.html" title="">jungleland</a></h1>		
		<p id="slogan">Just Another Styleshout CSS Template... </p>					
		
		<div id="nav">
			<ul>
				<li id="current"><a href="index.html">Home</a></li>
				<li><a href="style.html">Style Demo</a></li>
				<li><a href="blog.html">Blog</a></li>
				<li><a href="archives.html">Archives</a></li>
				<li><a href="index.html">Support</a></li>
				<li><a href="index.html">About</a></li>		
			</ul>		
		</div>		
		
		<p id="rss-feed"><a href="index.html" class="feed">Grab the RSS FEEd</a></p>	
		
		<form id="quick-search" action="index.html" method="get">
			<p>
			<label for="qsearch">Search:</label>
			<input class="tbox" id="qsearch" type="text" name="qsearch" value="Search..." title="Start typing and hit ENTER" />
			<input class="btn" alt="Search" type="image" name="searchsubmit" title="Search" src="/images/search.png" />
			</p>
		</form>	
						
	<!-- /header -->					
	</div>
	
	<!-- featured -->		
	<div id="featured">			
	
		<div id="featured-block" class="clear">
			
			<div id="featured-ribbon"></div>	
				
			<a name="TemplateInfo"></a>
			
			<div class="image-block">
              <a href="index.html" title=""><img src="/images/img-featured.jpg" alt="featured" width="350px" height="250px" /></a>
         </div>			
			
			<div class="text-block">
			
				<h2><a href="index.html">Read me first</a></h2>
			
				<p class="post-info">Posted by <a href="index.html">erwin</a> | Filed under <a href="index.html">templates</a>, <a href="index.html">internet</a></p>
				
				<p><strong>JungleLand 1.0</strong> is a free, W3C-compliant, CSS-based website template
				by <a href="http://www.styleshout.com/">styleshout.com</a>. This work is 
				distributed under the <a rel="license" href="http://creativecommons.org/licenses/by/2.5/">
				Creative Commons Attribution 2.5  License</a>, which means that you are free to 
				use and modify it for any purpose. All I ask is that you give me credit for the design by including a <strong>link back</strong> to
				<a href="http://www.styleshout.com/">my website</a>.
                </p>

                <p>
                You can find more of my free template designs at <a href="http://www.styleshout.com/">my website</a>.
				For premium commercial designs, you can check out
                <a href="http://www.dreamtemplate.com" title="Website Templates">DreamTemplate.com</a>.
				</p>
				
				<p><a href="index.html" class="more-link">Read More</a></p>
								
			</div>
		
		</div>		
	
	<!-- /featured -->
	</div>

	<!-- content -->
	<div id="content-wrap" class="clear">

		<div id="content">

			<!-- main -->
			<%= yield %>
		
			<!-- sidebar -->
			<div id="sidebar">
							
				<div class="sidemenu">
					<h3>Sidebar Menu</h3>
					<ul>				
						<li><a href="index.html">Home</a></li>
						<li><a href="index.html#TemplateInfo">TemplateInfo</a></li>
						<li><a href="style.html">Style Demo</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li><a href="archives.html">Archives</a></li>
						<li><a href="http://www.dreamtemplate.com/" title="Web Templates">Web Templates</a></li>
					</ul>	
				</div>
							
				<div class="sidemenu">
					<h3>Sponsors</h3>
					<ul>
						<li><a href="http://www.dreamtemplate.com" title="Website Templates">DreamTemplate</a><span>Over 6,000+ Premium Web Templates</span></li>
						<li><a href="http://www.themelayouts.com" title="WordPress Themes">ThemeLayouts</a><span>Premium WordPress &amp; Joomla Themes</span></li>
						<li><a href="http://www.imhosted.com" title="Website Hosting">ImHosted.com</a><span>Affordable Web Hosting Provider</span></li>
						<li><a href="http://www.dreamstock.com" title="Stock Photos">DreamStock</a><span>Download Amazing Stock Photos</span></li>
						<li><a href="http://www.evrsoft.com" title="Website Builder">Evrsoft</a><span>Website Builder Software &amp; Tools</span></li>
						<li><a href="http://www.webhostingwp.com" title="Web Hosting">Web Hosting</a><span>Top 10 Hosting Reviews</span></li>
					</ul>
				</div>
				
				<h3>Image Gallery </h3>					
				
				<p class="thumbs">
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>	
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>
					<a href="index.html"><img src="/images/thumb.jpg" width="40" height="40" alt="thumbnail" /></a>				
				</p>					
				
			<!-- /sidebar -->				
			</div>		
			
		<!-- /content -->	
		</div>				
	<!-- /content-wrap -->	
	</div>
<!-- /wrap -->
</div>

<!-- footer -->	
<div id="footer">	

	<!-- footer-outer -->	
	<div id="footer-outer" class="clear"><div id="footer-wrap">
	
		<div class="col-a">
				
			<h3>Contact Info</h3>
			
			<p>
			<strong>Phone: </strong>+1234567<br />
			<strong>Fax: </strong>+123456789
			</p>
			
			<p><strong>Address: </strong>123 Put Your Address Here</p>
				
			<p><strong>E-mail: </strong>me@jungleland.com</p>
			<p>Want more info - go to our <a href="#">contact page</a></p>			
			
			<h3>Follow Us</h3>
			
			<div class="footer-list">
				<ul>				
					<li><a href="index.html" class="rssfeed">RSS Feed</a></li>
					<li><a href="index.html" class="email">Email</a></li>
					<li><a href="index.html" class="twitter">Twitter</a></li>									
				</ul>
			</div>					
				
		</div>
		
		<div class="col-a">			
			
			<h3>Site Links</h3>
			
			<div class="footer-list">
				<ul>				
					<li><a href="index.html">Home</a></li>
					<li><a href="index.html">Style Demo</a></li>
					<li><a href="index.html">Blog</a></li>
					<li><a href="index.html">Archive</a></li>
					<li><a href="index.html">About</a></li>		
					<li><a href="index.html">Template Info</a></li>		
					<li><a href="index.html">Site Map</a></li>					
				</ul>
			</div>					
				
		</div>
		
		<div class="col-a">
		
			<h3>Web Resource</h3>
			
			<p>Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
			posuere nunc justo tempus leo. </p>
			
			<div class="footer-list">
				<ul>
                    <li><a href="http://www.dreamtemplate.com" title="Website Templates">DreamTemplate</a></li>
					<li><a href="http://www.themelayouts.com" title="WordPress Themes">ThemeLayouts</a></li>
					<li><a href="http://www.imhosted.com" title="Website Hosting">ImHosted.com</a></li>
					<li><a href="http://www.dreamstock.com" title="Stock Photos">DreamStock</a></li>
					<li><a href="http://www.evrsoft.com" title="Website Builder">Evrsoft</a></li>
					<li><a href="http://www.webhostingwp.com" title="Web Hosting">Web Hosting</a></li>
				</ul>
			</div>			
				
		</div>		

		<div class="col-b">
		
			<h3>About</h3>			
			
			<p>
			<a href="index.html"><img src="/images/gravatar.jpg" width="40" height="40" alt="firefox" class="float-left" /></a>
			Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
			Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
			posuere nunc justo tempus leo. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
			Cras id urna. <a href="index.html">Learn more...</a>
			</p>			
			
		</div>		
		
		<div class="fix"></div>
		
		<!-- footer-bottom -->
		<div id="footer-bottom">
	
			<div class="bottom-left">
				<p>
				&copy; 2010 <strong>Copyright Info Here</strong>&nbsp; &nbsp; &nbsp;
				<a href="http://www.bluewebtemplates.com/" title="Website Templates">website templates</a> by <a href="http://www.styleshout.com/">styleshout</a>
				</p>
			</div>		
	
			<div class="bottom-right">
				<p>		
					<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | 
		   		    <a href="http://validator.w3.org/check/referer">XHTML</a>	|
					<a href="index.html">Home</a> |
					<strong><a href="#top" class="back-to-top">Back to Top</a></strong>								
				</p>
			</div>

		<!-- /footer-bottom -->		
		</div>
	
	<!-- /footer-outer -->		
	</div></div>		

<!-- /footer -->
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slides</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Base App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if current_user %>
            <li><a href="/users/sign_out" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> base_app</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/original_template/index.html.erb
<p>You are using named yields. Here are examples how to use them:</p>
<% content_for :head do -%>
  <script></script>
<% end -%>


<!-- original body content --><div id="main">

				<h3>Recent Articles</h3>

				<div class="block odd">

					<a title="" href="index.html"><img src="/images/thumb-1.jpg" class="thumbnail" alt="img" width="240px" height="100px" /></a>
				
					<div class="blk-top">
					
						<h4><a href="index.html">Aliquam Risus Justo Lorem Ipsum Dolor Sit Amet</a></h4>	
						<p><span class="datetime">August 27, 2009</span><a href="index.html" class="comment">2 Comments</a></p>
						
					</div>						
					
					<div class="blk-content">
						
						<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
						Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
						posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum 
						odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra 
						condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. 				
						</p>					
								
						<p><a class="more" href="index.html">continue reading &raquo;</a></p>
					
					</div>
				
				</div>
				
				<div class="block even">
				
					<a title="" href="index.html"><img src="/images/thumb-2.jpg" class="thumbnail" alt="img" width="240px" height="100px" /></a>
				
					<div class="blk-top">
					
						<h4><a href="index.html">Aliquam Risus Justo</a></h4>	
						<p><span class="datetime">August 26, 2009</span> <a href="index.html" class="comment">2 Comments</a></p>
						
					</div>						
					
					<div class="blk-content">
						
						<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
						Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
						posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum 
						odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra 
						condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. 	
						
						<a class="more" href="index.html">continue reading &raquo;</a>			
						</p>
						
						<p></p>
					
					</div>
				
				</div>
				
				<div class="fix"></div>
						
				<div class="block odd">
				
					<a title="" href="index.html"><img src="/images/thumb-3.jpg" class="thumbnail" alt="img" width="240px" height="100px" /></a>
				
					<div class="blk-top">
					
						<h4><a href="index.html">Justo Lorem Ipsum Dolor Sit Amet</a></h4>	
						<p><span class="datetime">August 26, 2009</span> <a href="index.html" class="comment">2 Comments</a></p>
						
					</div>						
					
					<div class="blk-content">
						
						<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
						Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
						posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum 
						odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra 
						condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. 				
						</p>
								
						<p><a class="more" href="index.html">continue reading &raquo;</a></p>
					
					</div>
				
				</div>
				
				<div class="block even">
				
					<a title="" href="index.html"><img src="/images/thumb-4.jpg" class="thumbnail" alt="img" width="240px" height="100px" /></a>
				
					<div class="blk-top">
					
						<h4><a href="index.html">Aliquam Risus Justo</a></h4>	
						<p><span class="datetime">August 25, 2009</span> <a href="index.html" class="comment">2 Comments</a></p>
						
					</div>						
					
					<div class="blk-content">
						
						<p>
						Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. 
						Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu 
						posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum 
						odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra 
						condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. 				
						</p>
								
						<p><a class="more" href="index.html">continue reading &raquo;</a></p>
					
					</div>
				
				</div>
				
				<div class="fix"></div>			
			
			<!-- /main -->	
			</div>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/shared/permission_denied.html.erb
<h3>Sorry, you do not have access to the resource requested.</h3>